language: rust
rust:
    - stable
    - beta
    - nightly
    - 1.15.0 # Minimum supported version
os:
    - linux
    - osx
matrix:
    allow_failures:
        - rust: nightly
notifications:
    email: no
